### ISSUE TITLE
Python Migration

### ISSUE THREAD

**Issue by kwokcb** [kwokcb/MaterialX_Learn#163]
## Tasks

- [ ] core library migration (mtlxutils)
- [ ] publishing. 
   - [x] Updated and matching JS.
- [ ] notebook migration
- [ ] blender / maya / houdini tools migration
- [ ] doc / library compare util migration
- [ ] graph connectivity migration
- [ ] mermaid graph library migration
- [ ] shader generation migration
- [ ] renderer migration
- [ ] def graph generation migration
- [x] ocio codegen migration
- [ ] USDShade interop migration
- [ ] topology tools migration
- [x] JSON migration
- [ ] reference builder migration (TBD)
- [ ] glossary builder migration (TBD)
