### ISSUE TITLE
Javascript Migration

### ISSUE THREAD

**Issue by kwokcb** [kwokcb/MaterialX_Learn#164]
## Tasks

- [x] Utilities migration
- [x] glTF viewer migration
- [x] Mermaid viewer migration
- [x] model_viewer migration
